var verbs = [
	{letter: "A", first_form: "awake", second_form: "awoke", third_form: "awaken", translate: "a trezi"},
	{letter: "B", first_form: "be", second_form: "was/were", third_form: "been", translate: "a fi"},
	{letter: "B", first_form: "become", second_form: "became", third_form: "become", translate: "a deveni"},
	{letter: "B", first_form: "burnt", second_form: "burnt", third_form: "burn", translate: "a arde"},
	{letter: "B", first_form: "build", second_form: "built", third_form: "built", translate: "a construi"},
	{letter: "B", first_form: "bet", second_form: "bet", third_form: "bet", translate: "a paria"},
	{letter: "B", first_form: "buy", second_form: "bought", third_form: "bought", translate: "a cumpara"},
	{letter: "B", first_form: "bring", second_form: "brougt", third_form: "brought", translate: "a aduce"},
	{letter: "B", first_form: "break", second_form: "broke", third_form: "broken", translate: "a rupe, a sparge"},
	{letter: "B", first_form: "begin", second_form: "began", third_form: "begun", translate: "a incepe"},
	{letter: "B", first_form: "blow", second_form: "blew", third_form: "blown", translate: "a sufla"},
	{letter: "B", first_form: "bleed", second_form: "bled", third_form: "bled", translate: "a sangera"},
	{letter: "C", first_form: "cut", second_form: "cut", third_form: "cut", translate: "a taia"},
	{letter: "C", first_form: "cost", second_form: "cost", third_form: "cost", translate: "a costa"},
	{letter: "C", first_form: "choose", second_form: "chose", third_form: "chosen", translate: "a alege"},
	{letter: "C", first_form: "catch", second_form: "caught", third_form: "caught", translate: "a prinde"},
];
