var verbs = [
	{id: "1", first_form: "befehlen", second_form: "befahl", third_form: "befohlen", translate: "to command"},
	{id: "1", first_form: "beginnen", second_form: "begann", third_form: "begonnen", translate: "to begin"},
	{id: "1", first_form: "beissen", second_form: "biss", third_form: "gebissen", translate: "to bite"},
	{id: "1", first_form: "bergen", second_form: "barg", third_form: "geborgen", translate: "to rescue"},
	{id: "1", first_form: "biegen", second_form: "bog", third_form: "gebogen", translate: "to bend"},
	{id: "2", first_form: "bieten", second_form: "bot", third_form: "geboten", translate: "to offer"},
	{id: "2", first_form: "binden", second_form: "band", third_form: "gebunden", translate: "to bind"},
	{id: "2", first_form: "bitten", second_form: "bat", third_form: "gebeten", translate: "to request"},
	{id: "2", first_form: "blasen", second_form: "blies", third_form: "geblasen", translate: "to blow"},
	{id: "2", first_form: "bleiben", second_form: "blieb", third_form: "geblieben", translate: "to remain"},
	{id: "3", first_form: "braten", second_form: "briet", third_form: "gebraten", translate: "to fry"},
	{id: "3", first_form: "brechen", second_form: "brach", third_form: "gebrochen", translate: "to break"},
	{id: "3", first_form: "brennen", second_form: "brannte", third_form: "gebrannt", translate: "to burn"},
	{id: "3", first_form: "bringen", second_form: "brachte", third_form: "gebracht", translate: "to bring"},
	{id: "3", first_form: "denken", second_form: "dachte", third_form: "gedacht", translate: "to think"},
	{id: "4", first_form: "dreschen", second_form: "drosch", third_form: "gedroschen", translate: "to thrash"},
	{id: "4", first_form: "dringen", second_form: "drang", third_form: "gedrungen", translate: "to get through"},
	{id: "4", first_form: "dürfen", second_form: "durfte", third_form: "gedurft", translate: "to be allowed (may)"},
	{id: "4", first_form: "empfehlen", second_form: "empfahl", third_form: "empfohlen", translate: "to recommend"},
	{id: "4", first_form: "erschrecken", second_form: "erschrak", third_form: "erschrocken", translate: "to frighten"},
	{id: "5", first_form: "essen", second_form: "ass", third_form: "gegessen", translate: "to eat"},
	{id: "5", first_form: "erwägen", second_form: "erwog", third_form: "erwogen", translate: "to consider"},
	{id: "5", first_form: "fahren", second_form: "fuhr", third_form: "gefahren", translate: "to drive"},
	{id: "5", first_form: "fallen", second_form: "fiel", third_form: "gefallen", translate: "to fall"},
	{id: "5", first_form: "fangen", second_form: "fing", third_form: "gefangen", translate: "to catch"},
	{id: "6", first_form: "finden", second_form: "fand", third_form: "gefunden", translate: "to find"},
	{id: "6", first_form: "fliegen", second_form: "flog", third_form: "geflogen", translate: "to fly"},
	{id: "6", first_form: "fliehen", second_form: "floh", third_form: "geflohen", translate: "to flee"},
	{id: "6", first_form: "fliessen", second_form: "floss", third_form: "geflossen", translate: "to flow"},
	{id: "6", first_form: "fressen", second_form: "frass", third_form: "gefressen", translate: "to devour"},
	{id: "7", first_form: "frieren", second_form: "fror", third_form: "gefroren", translate: "to freeze"},
	{id: "7", first_form: "gären", second_form: "gor", third_form: "gegoren", translate: "to ferment"},
	{id: "7", first_form: "gebären", second_form: "gebar", third_form: "geboren", translate: "to bear"},
	{id: "7", first_form: "geben", second_form: "gab", third_form: "gegeben", translate: "to give"},
	{id: "7", first_form: "gedeihen", second_form: "gedieh", third_form: "gediehen", translate: "to thrive"},
	{id: "8", first_form: "gehen", second_form: "ging", third_form: "gegangen", translate: "to go"},
	{id: "8", first_form: "gelingen", second_form: "gelang", third_form: "gelungen", translate: "to be successful"},
	{id: "8", first_form: "gelten", second_form: "galt", third_form: "gegolten", translate: "to pertain"},
	{id: "8", first_form: "genesen", second_form: "genas", third_form: "genesen", translate: "to recover"},
	{id: "8", first_form: "geniessen", second_form: "genoss", third_form: "genossen", translate: "to enjoy"},
	{id: "9", first_form: "geschehen", second_form: "geschah", third_form: "geschehen", translate: "to happen"},
	{id: "9", first_form: "gewinnen", second_form: "gewann", third_form: "gewonnen", translate: "to win"},
	{id: "9", first_form: "giessen", second_form: "goss", third_form: "gegossen", translate: "to pour"},
	{id: "9", first_form: "gleichen", second_form: "glich", third_form: "geglichen", translate: "to resemble"},
	{id: "9", first_form: "gleiten", second_form: "glitt", third_form: "geglitten", translate: "to glide"},
	{id: "10", first_form: "graben", second_form: "grub", third_form: "gegraben", translate: "to dig"},
	{id: "10", first_form: "greifen", second_form: "griff", third_form: "gegriffen", translate: "to grasp"},
	{id: "10", first_form: "haben", second_form: "hatte", third_form: "gehabt", translate: "to have"},
	{id: "10", first_form: "halten", second_form: "hielt", third_form: "gehalten", translate: "to hold, to stop"},
	{id: "10", first_form: "hängen", second_form: "hing", third_form: "gehangen", translate: "to hang"},
	{id: "11", first_form: "hauen", second_form: "haute", third_form: "gehauen", translate: "to hit"},
	{id: "11", first_form: "heben", second_form: "hob", third_form: "gehoben", translate: "to lift"},
	{id: "11", first_form: "heissen", second_form: "hiess", third_form: "geheissen", translate: "to be called"},
	{id: "11", first_form: "helfen", second_form: "half", third_form: "geholfen", translate: "to help"},
	{id: "11", first_form: "kennen", second_form: "kannte", third_form: "gekannt", translate: "to know"},
	{id: "12", first_form: "klingen", second_form: "klang", third_form: "geklungen", translate: "to sound, to ring"},
	{id: "12", first_form: "kneifen", second_form: "kniff", third_form: "gekniffen", translate: "to pinch"},
	{id: "12", first_form: "kommen", second_form: "kam", third_form: "gekommen", translate: "to come"},
	{id: "12", first_form: "können", second_form: "konnte", third_form: "gekonnt", translate: "to can"},
	{id: "12", first_form: "kriechen", second_form: "kroch", third_form: "gekrochen", translate: "to crawl"},
	{id: "13", first_form: "laden", second_form: "lud", third_form: "geladen", translate: "to load"},
	{id: "13", first_form: "lassen", second_form: "liess", third_form: "gelassen", translate: "to let"},
	{id: "13", first_form: "laufen", second_form: "lief", third_form: "gelaufen", translate: "to run, walk"},
	{id: "13", first_form: "leiden", second_form: "litt", third_form: "gelitten", translate: "to suffer"},
	{id: "13", first_form: "leihen", second_form: "lieh", third_form: "geliehen", translate: "to lend, to borrow"},
	{id: "14", first_form: "lesen", second_form: "las", third_form: "gelesen", translate: "to read"},
	{id: "14", first_form: "liegen", second_form: "lag", third_form: "gelegen", translate: "to lie down"},
	{id: "14", first_form: "lügen", second_form: "log", third_form: "gelogen", translate: "to lie"},
	{id: "14", first_form: "meiden", second_form: "mied", third_form: "gemieden", translate: "to avoid"},
	{id: "14", first_form: "messen", second_form: "mass", third_form: "gemessen", translate: "to measure"},
	{id: "15", first_form: "misslingen", second_form: "misslang", third_form: "misslungen", translate: "to fail"},
	{id: "15", first_form: "mögen", second_form: "mochte", third_form: "gemocht", translate: "to like"},
	{id: "15", first_form: "müssen", second_form: "musste", third_form: "gemusst", translate: "to have to (must)"},
	{id: "15", first_form: "nehmen", second_form: "nahm", third_form: "genommen", translate: "to take"},
	{id: "15", first_form: "nennen", second_form: "nannte", third_form: "genannt", translate: "to call, name"},
	{id: "16", first_form: "pfeifen", second_form: "pfiff", third_form: "gepfiffen", translate: "to whistle"},
	{id: "16", first_form: "preisen", second_form: "pries", third_form: "gepriesen", translate: "to praise"},
	{id: "16", first_form: "quellen", second_form: "quoll", third_form: "gequollen", translate: "to gush"},
	{id: "16", first_form: "raten", second_form: "riet", third_form: "geraten", translate: "to guess, to advise"},
	{id: "16", first_form: "reiben", second_form: "rieb", third_form: "gerieben", translate: "to rub"},
	{id: "17", first_form: "reissen", second_form: "riss", third_form: "gerissen", translate: "to rip"},
	{id: "17", first_form: "reiten", second_form: "ritt", third_form: "geritten", translate: "to ride"},
	{id: "17", first_form: "rennen", second_form: "rannte", third_form: "gerannt", translate: "to run, race"},
	{id: "17", first_form: "riechen", second_form: "roch", third_form: "gerochen", translate: "to smell"},
	{id: "17", first_form: "ringen", second_form: "rang", third_form: "gerungen", translate: "to struggle"},
	{id: "17", first_form: "rinnen", second_form: "rann", third_form: "geronnen", translate: "to trickle"},
	{id: "18", first_form: "rufen", second_form: "rief", third_form: "gerufen", translate: "to call"},
	{id: "18", first_form: "saufen", second_form: "soff", third_form: "gesoffen", translate: "to guzzle, to tipple"},
	{id: "18", first_form: "schaffen", second_form: "schuf", third_form: "geschaffen", translate: "to create, to accomplish"},
	{id: "18", first_form: "scheiden", second_form: "schied", third_form: "geschieden", translate: "to separate"},
	{id: "18", first_form: "scheinen", second_form: "schien", third_form: "geschienen", translate: "to shine, to seem"},
	{id: "19", first_form: "schelten", second_form: "schalt", third_form: "gescholten", translate: "to scold"},
	{id: "19", first_form: "scheren", second_form: "schor", third_form: "geschoren", translate: "to shear"},
	{id: "19", first_form: "schieben", second_form: "schob", third_form: "geschoben", translate: "to push"},
	{id: "19", first_form: "schiessen", second_form: "schoss", third_form: "geschossen", translate: "to shoot"},
	{id: "19", first_form: "schinden", second_form: "schindete", third_form: "geschunden", translate: "to overwork [someone]"},
	{id: "20", first_form: "schlafen", second_form: "schlief", third_form: "geschlafen", translate: "to sleep"},
	{id: "20", first_form: "schlagen", second_form: "schlug", third_form: "geschlagen", translate: "to hit, strike"},
	{id: "20", first_form: "schleichen", second_form: "schlich", third_form: "geschlichen", translate: "to sneak"},
	{id: "20", first_form: "schliessen", second_form: "schloss", third_form: "geschlossen", translate: "to close"},
	{id: "20", first_form: "schlingen", second_form: "schlang", third_form: "geschlungen", translate: "to loop, to gulp"},
	{id: "21", first_form: "schmeissen", second_form: "schmiss", third_form: "geschmissen", translate: "to throw, fling"},
	{id: "21", first_form: "schmelzen", second_form: "schmolz", third_form: "geschmolzen", translate: "to melt"},
	{id: "21", first_form: "schneiden", second_form: "schnitt", third_form: "geschnitten", translate: "to cut"},
	{id: "21", first_form: "schreiben", second_form: "schrieb", third_form: "geschrieben", translate: "to write"},
	{id: "21", first_form: "schreien", second_form: "schrie", third_form: "geschrien", translate: "to scream, cry"},
	{id: "22", first_form: "schreiten", second_form: "schritt", third_form: "geschritten", translate: "to stride, step"},
	{id: "22", first_form: "schweigen", second_form: "schwieg", third_form: "geschwiegen", translate: "to be silent"},
	{id: "22", first_form: "schwellen", second_form: "schwoll", third_form: "geschwollen", translate: "to swell"},
	{id: "22", first_form: "schwimmen", second_form: "schwamm", third_form: "geschwommen", translate: "to swim"},
	{id: "22", first_form: "schwinden", second_form: "schwand", third_form: "geschwunden", translate: "to fade, disappear"},
	{id: "23", first_form: "schwingen", second_form: "schwang", third_form: "geschwungen", translate: "to sway, to wield"},
	{id: "23", first_form: "schwören", second_form: "schwor", third_form: "geschworen", translate: "to swear"},
	{id: "23", first_form: "sehen", second_form: "sah", third_form: "gesehen", translate: "to see"},
	{id: "23", first_form: "sein", second_form: "war", third_form: "gewesen", translate: "to be"},
	{id: "23", first_form: "singen", second_form: "sang", third_form: "gesungen", translate: "to sing"},
	{id: "24", first_form: "sinken", second_form: "sank", third_form: "gesunken", translate: "to sink"},
	{id: "24", first_form: "sinnen", second_form: "sann", third_form: "gesonnen", translate: "to ponder"},
	{id: "24", first_form: "sitzen", second_form: "sass", third_form: "gesessen", translate: "to sit"},
	{id: "24", first_form: "sollen", second_form: "sollte", third_form: "gesollt", translate: "should"},
	{id: "24", first_form: "speien", second_form: "spie", third_form: "gespien", translate: "to spit"},
	{id: "25", first_form: "spinnen", second_form: "spann", third_form: "gesponnen", translate: "to spin, to be crazy"},
	{id: "25", first_form: "sprechen", second_form: "sprach", third_form: "gesprochen", translate: "to speak"},
	{id: "25", first_form: "spriessen", second_form: "spross", third_form: "gesprossen", translate: "to sprout"},
	{id: "25", first_form: "springen", second_form: "sprang", third_form: "gesprungen", translate: "to jump"},
	{id: "25", first_form: "stechen", second_form: "stach", third_form: "gestochen", translate: "to stab, prick"},
	{id: "26", first_form: "stehen", second_form: "stand", third_form: "gestanden", translate: "to stand"},
	{id: "26", first_form: "stehlen", second_form: "stahl", third_form: "gestohlen", translate: "to steal"},
	{id: "26", first_form: "steigen", second_form: "stieg", third_form: "gestiegen", translate: "to climb, mount"},
	{id: "26", first_form: "sterben", second_form: "starb", third_form: "gestorben", translate: "to die"},
	{id: "26", first_form: "streichen", second_form: "strich", third_form: "gestrichen", translate: "to cancel, delete"},
	{id: "27", first_form: "streiten", second_form: "stritt", third_form: "gestritten", translate: "to quarrel"},
	{id: "27", first_form: "tragen", second_form: "trug", third_form: "getragen", translate: "to carry, to wear"},
	{id: "27", first_form: "treffen", second_form: "traf", third_form: "getroffen", translate: "to meet"},
	{id: "27", first_form: "treiben", second_form: "trieb", third_form: "getrieben", translate: "to compel, drive"},
	{id: "27", first_form: "treten", second_form: "trat", third_form: "getreten", translate: "to step"},
	{id: "28", first_form: "trinken", second_form: "trank", third_form: "getrunken", translate: "to drink"},
	{id: "28", first_form: "trügen", second_form: "trog", third_form: "getrogen", translate: "to deceive"},
	{id: "28", first_form: "tun", second_form: "tat", third_form: "getan", translate: "to do"},
	{id: "28", first_form: "verderben", second_form: "verdarb", third_form: "verdorben", translate: "to spoil"},
	{id: "28", first_form: "vergessen", second_form: "vergass", third_form: "vergessen", translate: "to forget"},
	{id: "29", first_form: "verlieren", second_form: "verlor", third_form: "verloren", translate: "to lose"},
	{id: "29", first_form: "wachsen", second_form: "wuchs", third_form: "gewachsen", translate: "to grow"},
	{id: "29", first_form: "waschen", second_form: "wusch", third_form: "gewaschen", translate: "to wash"},
	{id: "29", first_form: "weichen", second_form: "wich", third_form: "gewichen", translate: "to yield, give way"},
	{id: "29", first_form: "weisen", second_form: "wies", third_form: "gewiesen", translate: "to indicate"},
	{id: "30", first_form: "werben", second_form: "warb", third_form: "geworben", translate: "to advertise"},
	{id: "30", first_form: "werden", second_form: "wurde", third_form: "geworden", translate: "to become"},
	{id: "30", first_form: "werfen", second_form: "warf", third_form: "geworfen", translate: "to throw"},
	{id: "30", first_form: "wiegen", second_form: "wog", third_form: "gewogen", translate: "to weigh, to cradle"},
	{id: "30", first_form: "wissen", second_form: "wusste", third_form: "gewusst", translate: "to know (a fact)"},
	{id: "31", first_form: "wollen", second_form: "wollte", third_form: "gewollt", translate: "to want"},
	{id: "31", first_form: "wringen", second_form: "wrang", third_form: "gewrungen", translate: "to wring"},
	{id: "31", first_form: "ziehen", second_form: "zog", third_form: "gezogen", translate: "to pull, to move"},
	{id: "31", first_form: "zwingen", second_form: "zwang", third_form: "gezwungen", translate: "to force"},
];
